# -*- coding: utf-8 -*-
"""Eli.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zTjdBneFo0wuFNu_Dl4HPX9n-uXjxosA
"""

!pip install googletrans==4.0.0-rc1
!pip install transformers

import random
from googletrans import Translator
from transformers import pipeline

# Create a translator instance
translator = Translator()

# Define the languages you want to support
supported_languages = ["en", "fr", "es", "de", "it"]

# Create a function to translate text
def translate_text(text, target_language):
    translation = translator.translate(text, dest=target_language)
    return translation.text

# Create a function to initialize the chatbot
def initialize_chatbot():
    print("Chatbot: Hello! I am a language translator chatbot. You can ask me to translate text.")
    print("Chatbot: Type 'exit' to end the conversation.")
    print("Chatbot: Please enter the language you want to translate to (e.g., 'en' for English).")

# Create a function to handle user input and generate responses
def chatbot_conversation():
    user_input = input("You: ")

    if user_input.lower() == 'exit':
        print("Chatbot: Goodbye!")
        return False

    if user_input in supported_languages:
        target_language = user_input
        print(f"Chatbot: You've selected {target_language} language for translation.")
    else:
        target_language = random.choice(supported_languages)
        print(f"Chatbot: You haven't specified a language, so I'll translate to a random language: {target_language}")

    user_input = input("You: ")

    while user_input.lower() != 'exit':
        translation = translate_text(user_input, target_language)
        print(f"Chatbot: Translation to {target_language}: {translation}")
        user_input = input("You: ")

    print("Chatbot: Goodbye!")

# Main conversation loop
initialize_chatbot()
chatbot_conversation()